# <font color ='545aa7'> NOTEBOOK 2B: NumPy </font>

The document is copyright © 2021 Charles J. Weiss and is released under under the [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

# Library - NumPy
---
"*NumPy*"  is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

In [ ]:
import numpy as np

## 4.1 NumPy Arrays
### 4.1.1 Basic Arrays

In [ ]:
nums = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
for value in nums:
    print(2 * value)

0
2
4
6
8
10
12
14
16
18


In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(2 * arr)

[ 0  2  4  6  8 10 12 14 16 18]


### 4.1.2 Type Conversion to Arrays

In [ ]:
a = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]  # list
arr = np.array(a)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 4.1.3 Array from Sequence

In [ ]:
arr = np.arange(0, 10, 0.5)
arr

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
arr = np.linspace(0,10, 20)
arr

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [ ]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
arr = np.zeros((2,4))
arr += 3
print(arr)

[[3. 3. 3. 3.]
 [3. 3. 3. 3.]]


### 4.1.4 Arrays from Functions

In [ ]:
def prod(x, y):
    return x * y

In [ ]:
np.fromfunction(prod, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

## 4.2 Reshaping & Merging Arrays

In [ ]:
counting = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
counting.size

6

In [ ]:
counting.shape

(2, 3)

### 4.2.1 Reshaping Arrays

In [ ]:
array_1D = np.linspace(0, 9.5, 20)
array_1D

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
array_2D = np.reshape(array_1D, (4, 5))
array_2D

array([[0. , 0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. , 4.5],
       [5. , 5.5, 6. , 6.5, 7. ],
       [7.5, 8. , 8.5, 9. , 9.5]])

### 4.2.2 Flatten Arrays

In [ ]:
array_2D.flatten()

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

### 4.2.3 Transpose Arrays

In [ ]:
array_2D

array([[0. , 0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. , 4.5],
       [5. , 5.5, 6. , 6.5, 7. ],
       [7.5, 8. , 8.5, 9. , 9.5]])

In [ ]:
array_2D.T

array([[0. , 2.5, 5. , 7.5],
       [0.5, 3. , 5.5, 8. ],
       [1. , 3.5, 6. , 8.5],
       [1.5, 4. , 6.5, 9. ],
       [2. , 4.5, 7. , 9.5]])

### 4.2.4 Merge Arrays

In [ ]:
a = np.arange(0, 5)

In [ ]:
b = np.arange(5, 10)

In [ ]:
np.vstack((a, b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
np.hstack((a, b))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.dstack((a, b))

array([[[0, 5],
        [1, 6],
        [2, 7],
        [3, 8],
        [4, 9]]])

## 4.3 Indexing Arrays
### 4.3.1 One-Dimensional Arrays

In [ ]:
array_1D

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
array_1D[5]

2.5

### 4.3.2 Two-Dimensional Arrays

In [ ]:
array_2D

array([[0. , 0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. , 4.5],
       [5. , 5.5, 6. , 6.5, 7. ],
       [7.5, 8. , 8.5, 9. , 9.5]])

In [ ]:
array_2D[1]

array([2.5, 3. , 3.5, 4. , 4.5])

In [ ]:
array_2D[1][0]

2.5

In [ ]:
array_2D[1, 0]

2.5

In [ ]:
array_2D[1, 1:]

array([3. , 3.5, 4. , 4.5])

In [ ]:
array_2D[0] # implicitly understood all columns

array([0. , 0.5, 1. , 1.5, 2. ])

In [ ]:
array_2D[0, :] # explicit indicating all columns

array([0. , 0.5, 1. , 1.5, 2. ])

In [ ]:
array_2D[:, 0]     # all rows

array([0. , 2.5, 5. , 7.5])

## 4.4 Vectorization & Broadcasting
### 4.4.1 NumPy Functions

In [ ]:
squares = np.array([1, 4, 9, 16, 25])

In [ ]:
np.sqrt(squares)

array([1., 2., 3., 4., 5.])

### 4.4.2 Scalars & Arrays

In [ ]:
3 * np.array([[5, 6], [7, 8]])

array([[15, 18],
       [21, 24]])

In [ ]:
np.array([2]) + np.array([10, 20])

array([12, 22])

### 4.4.3 Arrays of the Same Dimensions

In [ ]:
a = np.array([[1,2], [3,4]]) 
b = np.array([[5,6], [7,8]]) 
a + b

array([[ 6,  8],
       [10, 12]])

### 4.4.4 Arrays of Different Dimensions

In [ ]:
a = np.array([[1,2], [3,4]])
b = np.array([2,2])
a + b

array([[3, 4],
       [5, 6]])

In [ ]:
a = np.array([[1,2], [3,4]])
b = np.array([2]) 
a * b

array([[2, 4],
       [6, 8]])

### 4.4.5 Vectorizing Python Functions

In [ ]:
def rate(k, conc):
    return k * conc

In [ ]:
rate(1.2, 0.80)

0.96

In [ ]:
concs = [0.1, 0.5, 1.0, 1.5, 2.0]

In [ ]:
vrate = np.vectorize(rate)

In [ ]:
vrate(1.2, concs)

array([0.12, 0.6 , 1.2 , 1.8 , 2.4 ])

## 4.5 Array Methods

In [ ]:
np.sqrt(4)

2.0

In [ ]:
np.sqrt(np.array([1, 4, 9]))

array([1., 2., 3.])